/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.bean.Filme;
import model.dao.FilmeDAO;

/**
 *
 * @author JVict
 */
public class ViewServicesFilmes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewServicesFilmes
     */
    public ViewServicesFilmes() {
        initComponents();
        readJTable();
    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableFilmes.getModel();
        modelo.setNumRows(0);
        FilmeDAO fdao = new FilmeDAO();
        for (Filme f : fdao.readFilmes()) {
            modelo.addRow(new Object[]{
                f.getIdFilme(),
                f.getTitulo(),
                f.getDiretor(),
                f.getGenero(),
                f.getIdioma(),
                f.getDuracao()
            });
        }
    }
    
    public void readJTableForSearch(String titulo) {
        DefaultTableModel modelo = (DefaultTableModel) jTableFilmes.getModel();
        modelo.setNumRows(0);
        FilmeDAO bdao = new FilmeDAO();
        for (Filme f : bdao.searchFilmes(titulo)) {
            modelo.addRow(new Object[]{
                f.getIdFilme(),
                f.getTitulo(),
                f.getDiretor(),
                f.getGenero(),
                f.getIdioma(),
                f.getDuracao()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelDiretor = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelIdioma = new javax.swing.JLabel();
        jLabelDuracao = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldDiretor = new javax.swing.JTextField();
        jTextFieldIdioma = new javax.swing.JTextField();
        jTextFieldGenero = new javax.swing.JTextField();
        jTextFieldDuracao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFilmes = new javax.swing.JTable();
        jButtonAdicionarFilmes = new javax.swing.JButton();
        jButtonAtualizarFilmes = new javax.swing.JButton();
        jButtonExcluirFilme = new javax.swing.JButton();
        jTextFieldBusca = new javax.swing.JTextField();
        jButtonBuscarFilmes = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Filmes");
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelTitulo.setText("Titulo:");

        jLabelDiretor.setText("Diretor:");

        jLabelGenero.setText("Gênero:");

        jLabelIdioma.setText("Idioma:");

        jLabelDuracao.setText("Duração:");

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });

        jTextFieldGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGeneroActionPerformed(evt);
            }
        });

        jTableFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Título", "Diretor", "Gênero", "Idioma", "Duração"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFilmesMouseClicked(evt);
            }
        });
        jTableFilmes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableFilmesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFilmes);

        jButtonAdicionarFilmes.setText("Adicionar");
        jButtonAdicionarFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarFilmesActionPerformed(evt);
            }
        });

        jButtonAtualizarFilmes.setText("Atualizar");
        jButtonAtualizarFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarFilmesActionPerformed(evt);
            }
        });

        jButtonExcluirFilme.setText("Excluir");
        jButtonExcluirFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirFilmeActionPerformed(evt);
            }
        });

        jTextFieldBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaActionPerformed(evt);
            }
        });

        jButtonBuscarFilmes.setText("Buscar");
        jButtonBuscarFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarFilmesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDuracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelDiretor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldDiretor))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelTitulo)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelGenero)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButtonAtualizarFilmes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAdicionarFilmes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonExcluirFilme))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIdioma)
                        .addGap(15, 15, 15)
                        .addComponent(jTextFieldIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarFilmes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarFilmes))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDiretor)
                            .addComponent(jTextFieldDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGenero))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabelIdioma))
                            .addComponent(jTextFieldIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDuracao)
                            .addComponent(jTextFieldDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtualizarFilmes)
                    .addComponent(jButtonAdicionarFilmes)
                    .addComponent(jButtonExcluirFilme))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jTextFieldGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGeneroActionPerformed

    private void jTableFilmesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableFilmesKeyReleased
        // TODO add your handling code here:
        if (jTableFilmes.getSelectedRow() != -1) {
            jTextFieldTitulo.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 1).toString());
            jTextFieldDiretor.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 2).toString());
            jTextFieldGenero.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 3).toString());
            jTextFieldIdioma.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 4).toString());
            jTextFieldDuracao.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_jTableFilmesKeyReleased

    private void jButtonAdicionarFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarFilmesActionPerformed
        // TODO add your handling code here:
        Filme f = new Filme();
        FilmeDAO dao = new FilmeDAO();
        f.setTitulo(jTextFieldTitulo.getText());
        f.setDiretor(jTextFieldDiretor.getText());
        f.setGenero(jTextFieldGenero.getText());
        f.setIdioma(jTextFieldIdioma.getText());
        f.setDuracao(Integer.parseInt(jTextFieldDuracao.getText()));
        dao.createFilme(f);
        readJTable();
    }//GEN-LAST:event_jButtonAdicionarFilmesActionPerformed

    private void jButtonAtualizarFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarFilmesActionPerformed
        // TODO add your handling code here:
        if (jTableFilmes.getSelectedRow() != -1) {
            Filme f = new Filme();
            FilmeDAO dao = new FilmeDAO();
            f.setTitulo(jTextFieldTitulo.getText());
            f.setDiretor(jTextFieldDiretor.getText());
            f.setGenero(jTextFieldGenero.getText());
            f.setIdioma(jTextFieldIdioma.getText());
            f.setDuracao(Integer.parseInt(jTextFieldDuracao.getText()));
            f.setIdFilme((int)jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 0));
            dao.updateFilme(f);
            readJTable();
        }
    }//GEN-LAST:event_jButtonAtualizarFilmesActionPerformed

    private void jButtonExcluirFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirFilmeActionPerformed
        // TODO add your handling code here:
        if (jTableFilmes.getSelectedRow() != -1) {
             Filme f = new Filme();
            FilmeDAO dao = new FilmeDAO();
      
            f.setIdFilme((int)jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 0));
            dao.deleteFilme(f);
            
            readJTable();
        }
    }//GEN-LAST:event_jButtonExcluirFilmeActionPerformed

    private void jTableFilmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFilmesMouseClicked
        // TODO add your handling code here:
        if (jTableFilmes.getSelectedRow() != -1) {
            jTextFieldTitulo.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 1).toString());
            jTextFieldDiretor.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 2).toString());
            jTextFieldGenero.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 3).toString());
            jTextFieldIdioma.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 4).toString());
            jTextFieldDuracao.setText(jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_jTableFilmesMouseClicked

    private void jTextFieldBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscaActionPerformed

    private void jButtonBuscarFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarFilmesActionPerformed
        // TODO add your handling code here:
        readJTableForSearch(jTextFieldBusca.getText());
    }//GEN-LAST:event_jButtonBuscarFilmesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarFilmes;
    private javax.swing.JButton jButtonAtualizarFilmes;
    private javax.swing.JButton jButtonBuscarFilmes;
    private javax.swing.JButton jButtonExcluirFilme;
    private javax.swing.JLabel jLabelDiretor;
    private javax.swing.JLabel jLabelDuracao;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelIdioma;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFilmes;
    private javax.swing.JTextField jTextFieldBusca;
    private javax.swing.JTextField jTextFieldDiretor;
    private javax.swing.JTextField jTextFieldDuracao;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldIdioma;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
